CREATE TABLE DVD (
    id INT AUTO_INCREMENT,
    title VARCHAR NOT NULL(35),
    genre VARCHAR NOT NULL(35),
    duration VARCHAR NOT NULL(20),
    leadActor VARCHAR NOT NULL(35),
    leadActress VARCHAR NOT NULL(35)
);